apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-qa
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/danbibeo/argocd-arfifacts.git
    targetRevision: HEAD
    path: qa
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp-qa

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true